# Generated by Django 5.0 on 2023-12-31 06:53

import django.core.validators
import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=store.models._get_file_name, validators=[django.core.validators.FileExtensionValidator(['jpg', 'png']), store.models.image_dims_validator]),
        ),
    ]
