# Generated by Django 5.0 on 2024-01-12 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_invoiceitem_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('refid', models.CharField(max_length=255)),
                ('state', models.IntegerField(choices=[(1, 'Pending'), (2, 'Paid')], default=1)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='store.invoice')),
            ],
        ),
    ]
