# Generated by Django 5.0 on 2024-01-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='authority',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='gw_response',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='refid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='state',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Paid'), (3, 'Error')], default=1),
        ),
    ]
