# Generated by Django 5.0 on 2024-01-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_payment_authority_payment_gw_response_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
